language: python
python:
  - "2.7"
  - "3.6"

sudo: required

cache:
  directories:
  - $HOME/.m2

install:
  - sudo apt-get -qq update
  - sudo apt-get install -y protobuf-compiler

before_script:
  - pip install sphinx pygments sphinxcontrib-inlinesyntaxhighlight

script:
  - make install-lexer build-doc-warning

notifications:
  email:
    recipients:
      - atzeinicola@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
